CREATE TABLE IF NOT EXISTS addresses (
	address_id int
		GENERATED BY DEFAULT AS IDENTITY
		PRIMARY KEY,
	country text,
	city text,
	street text
);

CREATE TABLE IF NOT EXISTS themes (
	theme_id int
		GENERATED BY DEFAULT AS IDENTITY
		PRIMARY KEY,
	name text
		NOT NULL,
	description text
);

CREATE TABLE IF NOT EXISTS compositions (
	composition_id int
		GENERATED BY DEFAULT AS IDENTITY
		PRIMARY KEY,
	title text
		NOT NULL,
	description text,
	published_date date
);

CREATE TABLE IF NOT EXISTS genders (
	gender_id int
		GENERATED BY DEFAULT AS IDENTITY
		PRIMARY KEY,
	gender text
		NOT NULL
		UNIQUE
);

CREATE TABLE IF NOT EXISTS poets (
	poet_id int
    	GENERATED BY DEFAULT AS IDENTITY
    	PRIMARY KEY,
	first_name text
		NOT NULL,
	last_name text 
		NOT NULL,
  	email text,
  	phone text,
	address_id int
		NOT NULL
		REFERENCES addresses,
  	gender_id int
    	NOT NULL
    	REFERENCES genders
);

CREATE TABLE IF NOT EXISTS poet_compositions (
	poet_compositions_id int
		GENERATED BY DEFAULT AS IDENTITY
		PRIMARY KEY,
	poet_id int
		NOT NULL
		REFERENCES poets,
	composition_id int
		NOT NULL
		REFERENCES compositions
);

CREATE TABLE IF NOT EXISTS competitions (
	competition_id int
		GENERATED BY DEFAULT AS IDENTITY
		PRIMARY KEY,
	theme_id int
		NOT NULL
		REFERENCES themes,
	address_id int
		NOT NULL
		REFERENCES addresses,
	visitors_number int,
	start_date date
		NOT NULL,
	end_date date
);

CREATE TABLE IF NOT EXISTS competitions_poets (
	competitions_poets_id int
		GENERATED BY DEFAULT AS IDENTITY
		PRIMARY KEY,
	competition_id int
		NOT NULL
		REFERENCES competitions,
	poet_id int
		NOT NULL
		REFERENCES poets,
	points int
		NOT NULL,
	performance_date date
		NOT NULL
);